/**
 * MVP-1 data shapes — strict 1:1 with `data/schema.sql`.
 *
 * Every field is deterministically derivable from the upstream source.
 * Nothing in here is generated by an LLM.
 */

export type Instancja =
  | "SR" // Sąd Rejonowy
  | "SO" // Sąd Okręgowy
  | "SA" // Sąd Apelacyjny
  | "SN" // Sąd Najwyższy
  | "NSA" // Naczelny Sąd Administracyjny
  | "WSA" // Wojewódzki Sąd Administracyjny
  | "TK" // Trybunał Konstytucyjny
  | "TSUE"; // Trybunał Sprawiedliwości UE

export type SentencjaTyp =
  | "oddala"
  | "uwzglednia"
  | "uchyla_przekazuje"
  | "zmienia"
  | "umarza"
  | "inne";

/** A single judgment row, decoded from the SQLite store. */
export interface Judgment {
  id: number;
  sygnatura: string;
  sygnatura_norm: string;
  sad: string;
  instancja: Instancja;
  data_orzeczenia: string;
  sentencja_typ: SentencjaTyp | null;
  prawomocny: 0 | 1 | null;
  uchylony_przez: string | null;
  podstawa_prawna: string[];
  zrodlo_url: string;
  data_pobrania: string;
  /** sha256 of the raw upstream `textContent` (audit; not exposed to MCP). */
  sha256: string;
}

/** Public, MCP-facing projection — excludes the audit hash. */
export interface JudgmentMatch {
  sygnatura: string;
  sad: string;
  instancja: Instancja;
  data_orzeczenia: string;
  sentencja_typ: SentencjaTyp | null;
  prawomocny: 0 | 1 | null;
  uchylony_przez: string | null;
  podstawa_prawna: string[];
  zrodlo_url: string;
  data_pobrania: string;
}

/**
 * verify_signature status codes.
 *
 *   FOUND         — exactly one match in the bundled corpus.
 *   NOT_FOUND     — zero matches, and the signature's shape does not look
 *                   like an instance that's outside our corpus scope.
 *                   Treat as "this citation is probably fabricated".
 *   AMBIGUOUS     — two or more matches share this signature (typically the
 *                   same case number reused by different courts).
 *   OUT_OF_SCOPE  — zero matches, BUT the signature's shape matches an
 *                   instance (SN / TSUE / NSA / TK) that is NOT covered by
 *                   the bundled corpus.  Treat as "we cannot say either way
 *                   — verify in source", NOT as a fabrication.
 */
export type VerifyStatus = "FOUND" | "NOT_FOUND" | "AMBIGUOUS" | "OUT_OF_SCOPE";

export interface VerifyResult {
  status: VerifyStatus;
  matches: JudgmentMatch[];
  /** Which instancje the bundled corpus actually covers — read from the manifest. */
  corpus_scope: Instancja[];
  /**
   * Only set when `status === "OUT_OF_SCOPE"`.  The instance our heuristic
   * believes the signature most likely belongs to, given its shape.  This
   * is a CLASSIFIER hint, not a fact about an actual court ruling.
   */
  likely_instancja?: Instancja;
  disclaimer: string;
}

/** Build-time metadata embedded in `data/judgments.db`. */
export interface Manifest {
  version: string;
  built_at: string;
  schema_version: number;
  total: number;
  source: string;
  legal_domain: string;
  seed_query_count: number;
  last_seed_at: string;
  /** Distinct `instancja` values present in the bundled corpus. */
  corpus_scope: Instancja[];
}
